"""Initiale Struktur für Projekte + Users

Revision ID: 05bcc8f50bb1
Revises: 
Create Date: 2025-08-01 16:22:30.554712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bcc8f50bb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'kunde', 'experte', name='roleenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('personentyp', sa.Enum('natuerliche_person', 'firma', name='personentypenum'), nullable=False),
    sa.Column('fachbereiche', sa.JSON(), nullable=True),
    sa.Column('berufsnachweis', sa.String(), nullable=True),
    sa.Column('mitarbeiteranzahl', sa.Integer(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('gewerbe', sa.String(), nullable=True),
    sa.Column('vorname', sa.String(), nullable=True),
    sa.Column('nachname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_planung', 'ausfuehrung', 'abgeschlossen', name='projectstatus'), nullable=True),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.Integer(), nullable=True),
    sa.Column('ort', sa.String(length=255), nullable=False),
    sa.Column('gebaeudetyp', sa.String(length=255), nullable=False),
    sa.Column('kontrollart', sa.String(length=255), nullable=False),
    sa.Column('energienachweise', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
